import fs from 'node:fs';
const path = 'mvp-server-v021.ts';
let s = fs.readFileSync(path, 'utf8');
const constAnchor = "const IDEMPOTENCY_COLLECTION = 'mvp_video_idempotency';\n";
if (!s.includes(constAnchor)) throw new Error('collection anchor missing');
s = s.replace(constAnchor, constAnchor + "const CHATGPT_KEY_COLLECTION = 'mvp_chatgpt_api_keys';\n");
const routeAnchor = "  const previousVitest = process.env.VITEST;\n";
if (!s.includes(routeAnchor)) throw new Error('route anchor missing');
const route = `  app.post('/api/mvp/chatgpt/keys', async (_req, res) => {\n    try {\n      const db = getFirestoreInstance();\n      if (!db) return res.status(503).json({ error: { code: 'FIRESTORE_UNAVAILABLE', message: 'Firestore unavailable.' } });\n      const apiKey = 'zjg_' + crypto.randomBytes(32).toString('base64url');\n      const keyHash = sha256(apiKey);\n      const createdAt = Date.now();\n      await db.collection(CHATGPT_KEY_COLLECTION).doc(keyHash).create({ createdAt, revokedAt: null, purpose: 'chatgpt-actions-v1' });\n      return res.status(201).json({\n        apiKey,\n        createdAt,\n        warning: 'This key is shown once. Store it in the GPT Action Bearer API-key configuration; do not paste it into GPT instructions or source code.',\n      });\n    } catch (error: any) {\n      return res.status(500).json({ error: { code: 'CHATGPT_KEY_CREATE_FAILED', message: String(error?.message || error) } });\n    }\n  });\n\n`;
s = s.replace(routeAnchor, route + routeAnchor);
fs.writeFileSync(path, s);
console.log('ChatGPT pairing endpoint patched.');
